// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using RecrutamentoDiversidade.Data;

#nullable disable

namespace RecrutamentoDiversidade.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615015859_CriarTabelasIniciais")]
    partial class CriarTabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Candidato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasDefaultValueSql("SEQ_CANDIDATO.NEXTVAL");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurriculoUrl")
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Genero")
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<bool>("PessoaComDeficiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("RacaEtnia")
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Telefone")
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("TipoDeficiencia")
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_CANDIDATO_NET_EMAIL");

                    b.ToTable("TB_CANDIDATO_NET", (string)null);
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Candidatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasDefaultValueSql("SEQ_CANDIDATURA.NEXTVAL");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("CandidatoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("InscritoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Observacoes")
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<bool>("PrioridadeDiversidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(30)")
                        .HasDefaultValue("Inscrito");

                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.HasIndex("CandidatoId", "VagaId")
                        .IsUnique()
                        .HasDatabaseName("UK_CANDIDATURA_NET_UNICA");

                    b.ToTable("TB_CANDIDATURA_NET", (string)null);
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasDefaultValueSql("SEQ_USUARIO.NEXTVAL");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_USUARIO_NET_EMAIL");

                    b.ToTable("TB_USUARIO_NET", (string)null);
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Vaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasDefaultValueSql("SEQ_VAGA.NEXTVAL");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LocalTrabalho")
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("MetaDiversidadePct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5,2)")
                        .HasDefaultValue(30m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("Aberta");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_VAGA_NET", (string)null);
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Candidatura", b =>
                {
                    b.HasOne("RecrutamentoDiversidade.Models.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CANDIDATURA_NET_CANDIDATO");

                    b.HasOne("RecrutamentoDiversidade.Models.Vaga", "Vaga")
                        .WithMany("Candidaturas")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CANDIDATURA_NET_VAGA");

                    b.Navigation("Candidato");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Vaga", b =>
                {
                    b.HasOne("RecrutamentoDiversidade.Models.Usuario", "Usuario")
                        .WithMany("Vagas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VAGA_NET_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Candidato", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Usuario", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("RecrutamentoDiversidade.Models.Vaga", b =>
                {
                    b.Navigation("Candidaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
